# Book Recommender Project

Book Scrapped from [goodreads](https://www.goodreads.com/book/popular_by_date/2019).

Developed by: Bryan Calderon

Extracting the 10 most popular books per year!

#### Scrapping

* Loading libraries

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import re
from urllib.parse import urljoin

* Defining the entry

In [16]:
base_url = "https://www.goodreads.com"

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9"
}

* Preparing functions to get soup and to extract books by year

In [17]:
def get_soup(url, headers=headers, retries=3, sleep_time=3):
    """
    Requests a page and returns a BeautifulSoup object.
    If the request fails, it retries a few times before returning None.
    """
    for attempt in range(retries):
        try:
            response = requests.get(url, headers=headers, timeout=20)
            response.raise_for_status()
            return BeautifulSoup(response.text, "html.parser")
        
        except requests.exceptions.RequestException as e:
            print(f"Attempt {attempt + 1} failed for {url}")
            print(e)
            time.sleep(sleep_time)
    
    return None

In [24]:
def extract_books_from_year_page(year, books_per_year=10):
    """
    Extracts only likely book URLs from Goodreads popular books by year page.
    """
    url = f"https://www.goodreads.com/book/popular_by_date/{year}"
    soup = get_soup(url)
    
    if soup is None:
        return []
    
    links = soup.find_all("a", href=True)
    
    books = []
    seen_ids = set()
    
    for link in links:
        href = link["href"]
        text = link.get_text(" ", strip=True)
        
        if "/book/show/" not in href:
            continue
        
        # Remove empty or suspicious link texts
        if not text or len(text) < 3:
            continue
        
        # Skip ISBN-like numeric links
        if text.isdigit():
            continue
        
        # Skip weak generic texts
        bad_texts = {"here", "here.", "more", "less", "preview", "read more",
        "kindle", "amazon", "audible", "worldcat", "libraries", "ACE#1", "ACE #1"}
        if text.lower() in bad_texts:
            continue
        
        # Extract Goodreads book ID to avoid duplicates
        match = re.search(r"/book/show/(\d+)", href)
        
        if not match:
            continue
        
        book_id = match.group(1)
        
        if book_id in seen_ids:
            continue
        
        seen_ids.add(book_id)
        
        book_url = urljoin(base_url, href.split("?")[0])
        
        books.append({
            "source_year": year,
            "rank": len(books) + 1,
            "list_title": text,
            "book_url": book_url,
            "source": "Goodreads Popular by Year"
        })
        
        if len(books) == books_per_year:
            break
    
    return books

* Testing with 2024

In [25]:
books_2024 = extract_books_from_year_page(2023, books_per_year=10)
books_2024

[{'source_year': 2023,
  'rank': 1,
  'list_title': 'Fourth Wing (The Empyrean, #1)',
  'book_url': 'https://www.goodreads.com/book/show/61431922-fourth-wing',
  'source': 'Goodreads Popular by Year'},
 {'source_year': 2023,
  'rank': 2,
  'list_title': 'Iron Flame (The Empyrean, #2)',
  'book_url': 'https://www.goodreads.com/book/show/90202302-iron-flame',
  'source': 'Goodreads Popular by Year'},
 {'source_year': 2023,
  'rank': 3,
  'list_title': "The Housemaid's Secret (The Housemaid, #2)",
  'book_url': 'https://www.goodreads.com/book/show/62848145-the-housemaid-s-secret',
  'source': 'Goodreads Popular by Year'},
 {'source_year': 2023,
  'rank': 4,
  'list_title': 'Happy Place',
  'book_url': 'https://www.goodreads.com/book/show/61718053-happy-place',
  'source': 'Goodreads Popular by Year'},
 {'source_year': 2023,
  'rank': 5,
  'list_title': 'Powerless (The Powerless Trilogy, #1)',
  'book_url': 'https://www.goodreads.com/book/show/75513900-powerless',
  'source': 'Goodreads Popular by Year'},
 {'source_year': 2023,
  'rank': 6,
  'list_title': 'Yellowface',
  'book_url': 'https://www.goodreads.com/book/show/62047984-yellowface',
  'source': 'Goodreads Popular by Year'},
 {'source_year': 2023,
  'rank': 7,
  'list_title': 'None of This Is True',
  'book_url': 'https://www.goodreads.com/book/show/62334530-none-of-this-is-true',
  'source': 'Goodreads Popular by Year'},
 {'source_year': 2023,
  'rank': 8,
  'list_title': 'Divine Rivals (Letters of Enchantment, #1)',
  'book_url': 'https://www.goodreads.com/book/show/60784546-divine-rivals',
  'source': 'Goodreads Popular by Year'},
 {'source_year': 2023,
  'rank': 9,
  'list_title': 'Yours Truly (Part of Your World, #2)',
  'book_url': 'https://www.goodreads.com/book/show/61918816-yours-truly',
  'source': 'Goodreads Popular by Year'},
 {'source_year': 2023,
  'rank': 10,
  'list_title': 'The Seven Year Slip',
  'book_url': 'https://www.goodreads.com/book/show/62926938-the-seven-year-slip',
  'source': 'Goodreads Popular by Year'}]

* Given that everything is working. Now we continue with the rest of the scrapping!

#### Scrape top 10 book links from 1975 to 2024

In [26]:
start_year = 1975
end_year = 2024
books_per_year = 10

book_links_data = []
failed_years = []

for year in range(start_year, end_year + 1):
    print(f"Extracting books from year {year}...")
    
    books = extract_books_from_year_page(year, books_per_year)
    
    if len(books) == 0:
        print(f"No books found for year {year}")
        failed_years.append(year)
    else:
        book_links_data.extend(books)
    
    time.sleep(3)

Extracting books from year 1975...
Extracting books from year 1976...
Extracting books from year 1977...
Extracting books from year 1978...
Extracting books from year 1979...
Extracting books from year 1980...
Extracting books from year 1981...
Extracting books from year 1982...
Extracting books from year 1983...
Extracting books from year 1984...
Extracting books from year 1985...
Extracting books from year 1986...
Extracting books from year 1987...
Extracting books from year 1988...
Extracting books from year 1989...
Extracting books from year 1990...
Extracting books from year 1991...
Extracting books from year 1992...
Extracting books from year 1993...
Extracting books from year 1994...
Extracting books from year 1995...
Extracting books from year 1996...
Extracting books from year 1997...
Extracting books from year 1998...
Extracting books from year 1999...
Extracting books from year 2000...
Extracting books from year 2001...
Extracting books from year 2002...
Extracting books from year 2003...
Extracting books from year 2004...
Extracting books from year 2005...
Extracting books from year 2006...
Extracting books from year 2007...
Extracting books from year 2008...
Extracting books from year 2009...
Extracting books from year 2010...
Extracting books from year 2011...
Extracting books from year 2012...
Extracting books from year 2013...
Extracting books from year 2014...
Extracting books from year 2015...
Extracting books from year 2016...
Extracting books from year 2017...
Extracting books from year 2018...
Extracting books from year 2019...
Extracting books from year 2020...
Extracting books from year 2021...
Extracting books from year 2022...
Extracting books from year 2023...
Extracting books from year 2024...

In [27]:
df_book_links = pd.DataFrame(book_links_data)
df_book_links.head()

,source_year,rank,list_title,book_url,source
0,1975,1,’Salem’s Lot,https://www.goodreads.com/book/show/11590._Sal...,Goodreads Popular by Year
1,1975,2,Tuck Everlasting,https://www.goodreads.com/book/show/84981.Tuck...,Goodreads Popular by Year
2,1975,3,"Shōgun (Asian Saga, #1)",https://www.goodreads.com/book/show/52382796-s...,Goodreads Popular by Year
3,1975,4,Factotum,https://www.goodreads.com/book/show/497199.Fac...,Goodreads Popular by Year
4,1975,5,Discipline and Punish: The Birth of the Prison,https://www.goodreads.com/book/show/80369.Disc...,Goodreads Popular by Year

In [28]:
df_book_links["list_title"].value_counts()

list_title
ACE #1                                           4
The BFG                                          2
Matilda                                          2
’Salem’s Lot                                     1
Tuck Everlasting                                 1
                                                ..
Just for the Summer (Part of Your World, #3)     1
The Housemaid is Watching (The Housemaid, #3)    1
Quicksilver (Fae & Alchemy, #1)                  1
The Teacher                                      1
The Boyfriend                                    1
Name: count, Length: 495, dtype: int64

NOTE: There are errors on some title of the books

In [29]:
df_book_links.to_csv("data/raw/goodreads_book_links_by_year.csv", index=False)

* Helper functions for cleaning detail-page values

In [30]:
def clean_count(text):
    """
    Converts strings like '3,461,396 ratings' into 3461396.
    """
    if text is None:
        return None
    
    match = re.search(r"([\d,]+)", text)
    
    if match:
        return int(match.group(1).replace(",", ""))
    
    return None


def clean_average_rating(text):
    """
    Extracts rating like 4.16 from text.
    """
    if text is None:
        return None
    
    match = re.search(r"(\d+\.\d+)", text)
    
    if match:
        return float(match.group(1))
    
    return None


def clean_pages(text):
    """
    Extracts number of pages from text like '336 pages, Hardcover'.
    """
    if text is None:
        return None
    
    match = re.search(r"(\d+)\s+pages", text)
    
    if match:
        return int(match.group(1))
    
    return None

#### Extracting detailed metadata from one book page

In [31]:
def extract_book_details(book_url):
    """
    Extracts detailed metadata from a Goodreads book page.
    """
    soup = get_soup(book_url)
    
    if soup is None:
        return None
    
    # Title from detail page
    title_tag = soup.select_one('h1[data-testid="bookTitle"]')
    
    if title_tag:
        title = title_tag.get_text(" ", strip=True)
    else:
        title_tag = soup.find("h1")
        title = title_tag.get_text(" ", strip=True) if title_tag else None
    
    # Author
    author_tag = soup.select_one('a[href*="/author/show/"]')
    author = author_tag.get_text(" ", strip=True) if author_tag else None
    
    # Average rating
    average_rating = None
    rating_tag = soup.select_one("div.RatingStatistics__rating")
    
    if rating_tag:
        try:
            average_rating = float(rating_tag.get_text(strip=True))
        except ValueError:
            average_rating = None
    
    # Ratings and reviews count
    ratings_count = None
    reviews_count = None
    
    stats_container = soup.select_one("div.BookPageMetadataSection__ratingStats")
    
    if stats_container:
        stats_text = stats_container.get_text(" ", strip=True)
    else:
        stats_text = soup.get_text(" ", strip=True)
    
    ratings_match = re.search(r"([\d,]+)\s+ratings", stats_text)
    reviews_match = re.search(r"([\d,]+)\s+reviews", stats_text)
    
    if ratings_match:
        ratings_count = int(ratings_match.group(1).replace(",", ""))
    
    if reviews_match:
        reviews_count = int(reviews_match.group(1).replace(",", ""))
    
    # Description
    description = None
    description_tag = soup.select_one('[data-testid="description"]')
    
    if description_tag:
        description = description_tag.get_text(" ", strip=True)
    
    # Genres
    genre_tags = soup.select('a[href*="/genres/"]')
    genres = list(dict.fromkeys([
        g.get_text(" ", strip=True) 
        for g in genre_tags 
        if g.get_text(strip=True)
    ]))
    
    # Pages and publication date
    pages = None
    published_date = None
    
    details_text = soup.get_text(" ", strip=True)
    
    pages_match = re.search(r"(\d+)\s+pages", details_text)
    published_match = re.search(
        r"First published\s+([A-Za-z]+\s+\d{1,2},\s+\d{4}|[A-Za-z]+\s+\d{4}|\d{4})", 
        details_text
    )
    
    if pages_match:
        pages = int(pages_match.group(1))
    
    if published_match:
        published_date = published_match.group(1)
    
    # Image URL
    image_url = None
    image_tag = soup.select_one('img.ResponsiveImage')
    
    if image_tag:
        image_url = image_tag.get("src")
    
    return {
        "title": title,
        "author": author,
        "average_rating": average_rating,
        "ratings_count": ratings_count,
        "reviews_count": reviews_count,
        "description": description,
        "genres": ", ".join(genres) if genres else None,
        "pages": pages,
        "published_date": published_date,
        "image_url": image_url
    }

In [32]:
test_url = df_book_links.loc[0, "book_url"]

test_details = extract_book_details(test_url)

test_details

{'title': '’Salem’s Lot',
 'author': 'Stephen  King',
 'average_rating': 4.1,
 'ratings_count': 674093,
 'reviews_count': 28812,
 'description': "Librarian's Note: Alternate-cover edition for ISBN 0450031063 Thousands of miles away from the small township of 'Salem's Lot, two terrified people, a man and a boy, still share the secrets of those clapboard houses and tree-lined streets. They must return to 'Salem's Lot for a final confrontation with the unspeakable evil that lives on in the town.",
 'genres': 'Horror, Fiction, Vampires, Fantasy, Thriller, Paranormal, Audiobook',
 'pages': 483,
 'published_date': 'October 17, 1975',
 'image_url': 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1738025067i/11590.jpg'}

#### Final scrapping including all details

In [33]:
detailed_books = []
failed_books = []

for index, row in df_book_links.iterrows():
    print(f"Scraping details {index + 1}/{len(df_book_links)}: {row['book_url']}")
    
    details = extract_book_details(row["book_url"])
    
    if details is None:
        failed_books.append(row["book_url"])
        continue
    
    combined_data = {
        "source_year": row["source_year"],
        "rank": row["rank"],
        "list_title": row["list_title"],
        "book_url": row["book_url"],
        "source": row["source"]
    }
    
    combined_data.update(details)
    detailed_books.append(combined_data)
    
    time.sleep(4)

Scraping details 1/500: https://www.goodreads.com/book/show/11590._Salem_s_Lot
Scraping details 2/500: https://www.goodreads.com/book/show/84981.Tuck_Everlasting
Scraping details 3/500: https://www.goodreads.com/book/show/52382796-sh-gun
Scraping details 4/500: https://www.goodreads.com/book/show/497199.Factotum
Scraping details 5/500: https://www.goodreads.com/book/show/80369.Discipline_and_Punish
Scraping details 6/500: https://www.goodreads.com/book/show/40881649-crocodile-on-the-sandbank
Scraping details 7/500: https://www.goodreads.com/book/show/37743.Forever_
Scraping details 8/500: https://www.goodreads.com/book/show/43339.Where_Are_the_Children_
Scraping details 9/500: https://www.goodreads.com/book/show/95747.The_Miracle_of_Mindfulness
Scraping details 10/500: https://www.goodreads.com/book/show/6690.Danny_the_Champion_of_the_World
Scraping details 11/500: https://www.goodreads.com/book/show/43763.Interview_with_the_Vampire
Scraping details 12/500: https://www.goodreads.com/book/show/61535.The_Selfish_Gene
Scraping details 13/500: https://www.goodreads.com/book/show/44492286-children-of-dune
Scraping details 14/500: https://www.goodreads.com/book/show/546018.Roots
Scraping details 15/500: https://www.goodreads.com/book/show/310459.Roll_of_Thunder_Hear_My_Cry
Scraping details 16/500: https://www.goodreads.com/book/show/38743.All_Things_Bright_and_Beautiful
Scraping details 17/500: https://www.goodreads.com/book/show/226162.The_Omen
Scraping details 18/500: https://www.goodreads.com/book/show/53343.On_Writing_Well
Scraping details 19/500: https://www.goodreads.com/book/show/173673.A_Course_in_Miracles
Scraping details 20/500: https://www.goodreads.com/book/show/16300.Sleeping_Murder
Scraping details 21/500: https://www.goodreads.com/book/show/11588.The_Shining
Scraping details 22/500: https://www.goodreads.com/book/show/40940121-bridge-to-terabithia
Scraping details 23/500: https://www.goodreads.com/book/show/7332.The_Silmarillion
Scraping details 24/500: https://www.goodreads.com/book/show/3412.The_Thorn_Birds
Scraping details 25/500: https://www.goodreads.com/book/show/11334.Song_of_Solomon
Scraping details 26/500: https://www.goodreads.com/book/show/293101.The_Amityville_Horror
Scraping details 27/500: https://www.goodreads.com/book/show/14817.A_Scanner_Darkly
Scraping details 28/500: https://www.goodreads.com/book/show/15575.The_Sword_of_Shannara
Scraping details 29/500: https://www.goodreads.com/book/show/762390.The_Hour_of_the_Star
Scraping details 30/500: https://www.goodreads.com/book/show/147732.Miss_Nelson_Is_Missing_
Scraping details 31/500: https://www.goodreads.com/book/show/87591651-the-stand
Scraping details 32/500: https://www.goodreads.com/book/show/902.The_Westing_Game
Scraping details 33/500: https://www.goodreads.com/book/show/7069.The_World_According_to_Garp
Scraping details 34/500: https://www.goodreads.com/book/show/10628.Night_Shift
Scraping details 35/500: https://www.goodreads.com/book/show/92364.Eye_of_the_Needle
Scraping details 36/500: https://www.goodreads.com/book/show/347852.The_Road_Less_Traveled
Scraping details 37/500: https://www.goodreads.com/book/show/46945.Requiem_for_a_Dream
Scraping details 38/500: https://www.goodreads.com/book/show/8073.Cloudy_with_a_Chance_of_Meatballs
Scraping details 39/500: https://www.goodreads.com/book/show/38500.Women
Scraping details 40/500: https://www.goodreads.com/book/show/355190.Orientalism
Scraping details 41/500: https://www.goodreads.com/book/show/11.The_Hitchhiker_s_Guide_to_the_Galaxy
Scraping details 42/500: https://www.goodreads.com/book/show/60931.Kindred
Scraping details 43/500: https://www.goodreads.com/book/show/627206.The_New_Drawing_on_the_Right_Side_of_the_Brain
Scraping details 44/500: https://www.goodreads.com/book/show/9014.The_Long_Walk
Scraping details 45/500: https://www.goodreads.com/book/show/43448.Flowers_in_the_Attic
Scraping details 46/500: https://www.goodreads.com/book/show/27712.The_Neverending_Story
Scraping details 47/500: https://www.goodreads.com/book/show/11573.The_Dead_Zone
Scraping details 48/500: https://www.goodreads.com/book/show/374233.If_on_a_Winter_s_Night_a_Traveler
Scraping details 49/500: https://www.goodreads.com/book/show/40929.The_Rise_of_Theodore_Roosevelt
Scraping details 50/500: https://www.goodreads.com/book/show/24113.G_del_Escher_Bach
Scraping details 51/500: https://www.goodreads.com/book/show/119073.The_Name_of_the_Rose
Scraping details 52/500: https://www.goodreads.com/book/show/2767.A_People_s_History_of_the_United_States
Scraping details 53/500: https://www.goodreads.com/book/show/7869.The_Bourne_Identity
Scraping details 54/500: https://www.goodreads.com/book/show/310612.A_Confederacy_of_Dunces
Scraping details 55/500: https://www.goodreads.com/book/show/15195.The_Complete_Maus
Scraping details 56/500: https://www.goodreads.com/book/show/8695.The_Restaurant_at_the_End_of_the_Universe
Scraping details 57/500: https://www.goodreads.com/book/show/40611463-the-clan-of-the-cave-bear
Scraping details 58/500: https://www.goodreads.com/book/show/55030.Cosmos
Scraping details 59/500: https://www.goodreads.com/book/show/233667.Firestarter
Scraping details 60/500: https://www.goodreads.com/book/show/813214.The_Mist
Scraping details 61/500: https://www.goodreads.com/book/show/30118.A_Light_in_the_Attic
Scraping details 62/500: https://www.goodreads.com/book/show/28877.Red_Dragon
Scraping details 63/500: https://www.goodreads.com/book/show/10603.Cujo
Scraping details 64/500: https://www.goodreads.com/book/show/14836.Midnight_s_Children
Scraping details 65/500: https://www.goodreads.com/book/show/23878.Chronicle_of_a_Death_Foretold
Scraping details 66/500: https://www.goodreads.com/book/show/44439415-god-emperor-of-dune
Scraping details 67/500: https://www.goodreads.com/book/show/763362.The_One_Minute_Manager
Scraping details 68/500: https://www.goodreads.com/book/show/313605.Getting_to_Yes
Scraping details 69/500: https://www.goodreads.com/book/show/11438.What_We_Talk_About_When_We_Talk_About_Love
Scraping details 70/500: https://www.goodreads.com/book/show/635635.Women_Race_Class
Scraping details 71/500: https://www.goodreads.com/book/show/52892857-the-color-purple
Scraping details 72/500: https://www.goodreads.com/book/show/247642509-the-gunslinger
Scraping details 73/500: https://www.goodreads.com/book/show/6319.The_BFG
Scraping details 74/500: https://www.goodreads.com/book/show/9328.The_House_of_the_Spirits
Scraping details 75/500: https://www.goodreads.com/book/show/40605251-the-mists-of-avalon
Scraping details 76/500: https://www.goodreads.com/book/show/375013.Schindler_s_List
Scraping details 77/500: https://www.goodreads.com/book/show/39662.Different_Seasons
Scraping details 78/500: https://www.goodreads.com/book/show/8694.Life_the_Universe_and_Everything
Scraping details 79/500: https://www.goodreads.com/book/show/11607.The_Running_Man
Scraping details 80/500: https://www.goodreads.com/book/show/64863.A_Is_for_Alibi
Scraping details 81/500: https://www.goodreads.com/book/show/33124137-pet-sematary
Scraping details 82/500: https://www.goodreads.com/book/show/22047048
Scraping details 83/500: https://www.goodreads.com/book/show/34497.The_Color_of_Magic
Scraping details 84/500: https://www.goodreads.com/book/show/6327.The_Witches
Scraping details 85/500: https://www.goodreads.com/book/show/20407316.another_edition
Scraping details 86/500: https://www.goodreads.com/book/show/10629.Christine
Scraping details 87/500: https://www.goodreads.com/book/show/62022.The_Queen_s_Gambit
Scraping details 88/500: https://www.goodreads.com/book/show/13831.Alanna
Scraping details 89/500: https://www.goodreads.com/book/show/37034.The_Woman_in_Black
Scraping details 90/500: https://www.goodreads.com/book/show/225343.Heartburn
Scraping details 91/500: https://www.goodreads.com/book/show/9717.The_Unbearable_Lightness_of_Being
Scraping details 92/500: https://www.goodreads.com/book/show/6088007-neuromancer
Scraping details 93/500: https://www.goodreads.com/book/show/28815.Influence
Scraping details 94/500: https://www.goodreads.com/book/show/19691.The_Hunt_for_Red_October
Scraping details 95/500: https://www.goodreads.com/book/show/139253.The_House_on_Mango_Street
Scraping details 96/500: https://www.goodreads.com/book/show/10605.Thinner
Scraping details 97/500: https://www.goodreads.com/book/show/6091075-so-long-and-thanks-for-all-the-fish
Scraping details 98/500: https://www.goodreads.com/book/show/59219.The_Talisman
Scraping details 99/500: https://www.goodreads.com/book/show/10611.The_Eyes_of_the_Dragon
Scraping details 100/500: https://www.goodreads.com/book/show/567678.The_Wasp_Factory
Scraping details 101/500: https://www.goodreads.com/book/show/34454589-the-handmaid-s-tale
Scraping details 102/500: https://www.goodreads.com/book/show/375802.Ender_s_Game
Scraping details 103/500: https://www.goodreads.com/book/show/9712.Love_in_the_Time_of_Cholera
Scraping details 104/500: https://www.goodreads.com/book/show/343.Perfume
Scraping details 105/500: https://www.goodreads.com/book/show/256008.Lonesome_Dove
Scraping details 106/500: https://www.goodreads.com/book/show/63697.The_Man_Who_Mistook_His_Wife_for_a_Hat_and_Other_Clinical_Tales
Scraping details 107/500: https://www.goodreads.com/book/show/394535.Blood_Meridian_or_the_Evening_Redness_in_the_West
Scraping details 108/500: https://www.goodreads.com/book/show/35167685-surely-you-re-joking-mr-feynman
Scraping details 109/500: https://www.goodreads.com/book/show/767680.If_You_Give_a_Mouse_a_Cookie
Scraping details 110/500: https://www.goodreads.com/book/show/540654._If_You_Give_a_Mouse_a_Cookie___1985_
Scraping details 111/500: https://www.goodreads.com/book/show/6294.Howl_s_Moving_Castle
Scraping details 112/500: https://www.goodreads.com/book/show/15196.Maus_I
Scraping details 113/500: https://www.goodreads.com/book/show/7967.Speaker_for_the_Dead
Scraping details 114/500: https://www.goodreads.com/book/show/310259.Love_You_Forever
Scraping details 115/500: https://www.goodreads.com/book/show/16735.The_Prince_of_Tides
Scraping details 116/500: https://www.goodreads.com/book/show/17856572-watchmen-1
Scraping details 117/500: https://www.goodreads.com/book/show/59960.Batman
Scraping details 118/500: https://www.goodreads.com/book/show/34506.The_Light_Fantastic
Scraping details 119/500: https://www.goodreads.com/book/show/7996.Redwall
Scraping details 120/500: https://www.goodreads.com/book/show/15769.The_Bourne_Supremacy
Scraping details 121/500: https://www.goodreads.com/book/show/11297.Norwegian_Wood
Scraping details 122/500: https://www.goodreads.com/book/show/10614.Misery
Scraping details 123/500: https://www.goodreads.com/book/show/6149.Beloved
Scraping details 124/500: https://www.goodreads.com/book/show/472331.Watchmen
Scraping details 125/500: https://www.goodreads.com/book/show/50.Hatchet
Scraping details 126/500: https://www.goodreads.com/book/show/9375.Fried_Green_Tomatoes_at_the_Whistle_Stop_Cafe
Scraping details 127/500: https://www.goodreads.com/book/show/5094.The_Drawing_of_the_Three
Scraping details 128/500: https://www.goodreads.com/book/show/386372.Mort
Scraping details 129/500: https://www.goodreads.com/book/show/34507.Equal_Rites
Scraping details 130/500: https://www.goodreads.com/book/show/455373.Sphere
Scraping details 131/500: https://www.goodreads.com/book/show/18144590-the-alchemist
Scraping details 132/500: https://www.goodreads.com/book/show/39988.Matilda
Scraping details 133/500: https://www.goodreads.com/book/show/781822.Charlie_and_the_Chocolate_Factory
Scraping details 134/500: https://www.goodreads.com/book/show/28186304.Matilda
Scraping details 135/500: https://www.goodreads.com/book/show/527786.The_BFG
Scraping details 136/500: https://www.goodreads.com/book/show/3869.A_Brief_History_of_Time
Scraping details 137/500: https://www.goodreads.com/book/show/23807.The_Silence_of_the_Lambs
Scraping details 138/500: https://www.goodreads.com/book/show/23754.The_Sandman_Vol_1
Scraping details 139/500: https://www.goodreads.com/book/show/67238.Dead_Poets_Society
Scraping details 140/500: https://www.goodreads.com/book/show/59980.Batman
Scraping details 141/500: https://www.goodreads.com/book/show/36072.The_7_Habits_of_Highly_Effective_People
Scraping details 142/500: https://www.goodreads.com/book/show/5043.The_Pillars_of_the_Earth
Scraping details 143/500: http://www.goodreads.com/book/show/17229203-the-pillars-of-the-earth
Scraping details 144/500: https://www.goodreads.com/book/show/32542.A_Time_to_Kill
Scraping details 145/500: https://www.goodreads.com/book/show/7763.The_Joy_Luck_Club
Scraping details 146/500: https://www.goodreads.com/book/show/47281.Number_the_Stars
Scraping details 147/500: https://www.goodreads.com/book/show/28921.The_Remains_of_the_Day
Scraping details 148/500: https://www.goodreads.com/book/show/77566.Hyperion
Scraping details 149/500: https://www.goodreads.com/book/show/4473.A_Prayer_for_Owen_Meany
Scraping details 150/500: https://www.goodreads.com/book/show/6952.Like_Water_for_Chocolate
Scraping details 151/500: https://www.goodreads.com/book/show/12070.Good_Omens
Scraping details 152/500: https://www.goodreads.com/book/show/40604658-jurassic-park
Scraping details 153/500: https://www.goodreads.com/book/show/228665.The_Eye_of_the_World
Scraping details 154/500: https://www.goodreads.com/book/show/23878688-the-5-love-languages
Scraping details 155/500: https://www.goodreads.com/book/show/191139.Oh_the_Places_You_ll_Go_
Scraping details 156/500: https://www.goodreads.com/book/show/233093._Cat_in_the_Hat_
Scraping details 157/500: https://www.goodreads.com/book/show/133518.The_Things_They_Carried
Scraping details 158/500: https://www.goodreads.com/book/show/5805.V_for_Vendetta
Scraping details 159/500: https://www.goodreads.com/book/show/233649.The_Great_Hunt
Scraping details 160/500: https://www.goodreads.com/book/show/6534.Postmortem
Scraping details 161/500: https://www.goodreads.com/book/show/10964.Outlander
Scraping details 162/500: https://www.goodreads.com/book/show/28676.American_Psycho
Scraping details 163/500: https://www.goodreads.com/book/show/10959.Sophie_s_World
Scraping details 164/500: https://www.goodreads.com/book/show/11422.Redeeming_Love
Scraping details 165/500: https://www.goodreads.com/book/show/34897.The_Dragon_Reborn
Scraping details 166/500: https://www.goodreads.com/book/show/107291.Needful_Things
Scraping details 167/500: https://www.goodreads.com/book/show/34084.The_Waste_Lands
Scraping details 168/500: https://www.goodreads.com/book/show/1848.Wild_Swans
Scraping details 169/500: https://www.goodreads.com/book/show/8648.Xenocide
Scraping details 170/500: https://www.goodreads.com/book/show/452235.The_Firm
Scraping details 171/500: https://www.goodreads.com/book/show/29044.The_Secret_History
Scraping details 172/500: https://www.goodreads.com/book/show/5364.Dragonfly_in_Amber
Scraping details 173/500: https://www.goodreads.com/book/show/32499.The_Pelican_Brief
Scraping details 174/500: https://www.goodreads.com/book/show/61240297-snow-crash
Scraping details 175/500: https://www.goodreads.com/book/show/5203.She_s_Come_Undone
Scraping details 176/500: https://www.goodreads.com/book/show/241823.Women_Who_Run_With_the_Wolves
Scraping details 177/500: https://www.goodreads.com/book/show/9539.The_Shadow_Rising
Scraping details 178/500: https://www.goodreads.com/book/show/25454056-sword-of-destiny
Scraping details 179/500: https://www.goodreads.com/book/show/32508.The_Black_Echo
Scraping details 180/500: https://www.goodreads.com/book/show/32692.Gerald_s_Game
Scraping details 181/500: https://www.goodreads.com/book/show/3636.The_Giver
Scraping details 182/500: https://www.goodreads.com/book/show/10956.The_Virgin_Suicides
Scraping details 183/500: https://www.goodreads.com/book/show/52397.Parable_of_the_Sower
Scraping details 184/500: https://www.goodreads.com/book/show/40603587-the-last-wish
Scraping details 185/500: https://www.goodreads.com/book/show/51633549-the-last-wish
Scraping details 186/500: https://www.goodreads.com/book/show/13145.Along_Came_a_Spider
Scraping details 187/500: https://www.goodreads.com/book/show/68783.Girl_Interrupted
Scraping details 188/500: https://www.goodreads.com/book/show/5359.The_Client
Scraping details 189/500: https://www.goodreads.com/book/show/10987.Voyager
Scraping details 190/500: https://www.goodreads.com/book/show/23955.Trainspotting
Scraping details 191/500: https://www.goodreads.com/book/show/6853.One_for_the_Money
Scraping details 192/500: https://www.goodreads.com/book/show/11275.The_Wind_Up_Bird_Chronicle
Scraping details 193/500: https://www.goodreads.com/book/show/386187.Midnight_in_the_Garden_of_Good_and_Evil
Scraping details 194/500: https://www.goodreads.com/book/show/6043781-blood-of-elves
Scraping details 195/500: https://www.goodreads.com/book/show/13148.Kiss_the_Girls
Scraping details 196/500: https://www.goodreads.com/book/show/37004370-the-memory-police
Scraping details 197/500: https://www.goodreads.com/book/show/40024.The_Alienist
Scraping details 198/500: https://www.goodreads.com/book/show/43889.Wizard_s_First_Rule
Scraping details 199/500: https://www.goodreads.com/book/show/35231.Lord_of_Chaos
Scraping details 200/500: https://www.goodreads.com/book/show/77142.Snow_Falling_on_Cedars
Scraping details 201/500: https://www.goodreads.com/book/show/119322.The_Golden_Compass
Scraping details 202/500: https://www.goodreads.com/book/show/60811826-i-who-have-never-known-men
Scraping details 203/500: https://www.goodreads.com/book/show/37442.Wicked
Scraping details 204/500: https://www.goodreads.com/book/show/77197.Assassin_s_Apprentice
Scraping details 205/500: https://www.goodreads.com/book/show/5358.The_Firm
Scraping details 206/500: https://www.goodreads.com/book/show/60748.A_Child_Called_It_
Scraping details 207/500: https://www.goodreads.com/book/show/25862303
Scraping details 208/500: https://www.goodreads.com/book/show/40495148-blindness
Scraping details 209/500: https://www.goodreads.com/book/show/88061.Dreams_from_My_Father
Scraping details 210/500: https://www.goodreads.com/book/show/26329.Emotional_Intelligence
Scraping details 211/500: https://www.goodreads.com/book/show/13496.A_Game_of_Thrones
Scraping details 212/500: https://www.goodreads.com/book/show/33648131-the-notebook
Scraping details 213/500: https://www.goodreads.com/book/show/60869516-into-the-wild
Scraping details 214/500: https://www.goodreads.com/book/show/227443.Bridget_Jones_s_Diary
Scraping details 215/500: https://www.goodreads.com/book/show/36236124-fight-club
Scraping details 216/500: https://www.goodreads.com/book/show/14497.Neverwhere
Scraping details 217/500: https://www.goodreads.com/book/show/252577.Angela_s_Ashes
Scraping details 218/500: https://www.goodreads.com/book/show/11566.The_Green_Mile
Scraping details 219/500: https://www.goodreads.com/book/show/137791.Divine_Secrets_of_the_Ya_Ya_Sisterhood
Scraping details 220/500: https://www.goodreads.com/book/show/13.The_Ultimate_Hitchhiker_s_Guide_to_the_Galaxy
Scraping details 221/500: https://www.goodreads.com/book/show/42844155-harry-potter-and-the-philosopher-s-stone
Scraping details 222/500: https://www.goodreads.com/book/show/929.Memoirs_of_a_Geisha
Scraping details 223/500: https://www.goodreads.com/book/show/6900.Tuesdays_with_Morrie
Scraping details 224/500: https://www.goodreads.com/book/show/69571.Rich_Dad_Poor_Dad
Scraping details 225/500: https://www.goodreads.com/book/show/6596.The_Four_Agreements
Scraping details 226/500: https://www.goodreads.com/book/show/1842.Guns_Germs_and_Steel
Scraping details 227/500: https://www.goodreads.com/book/show/6708.The_Power_of_Now
Scraping details 228/500: https://www.goodreads.com/book/show/193893624-the-power-of-now
Scraping details 229/500: https://www.goodreads.com/book/show/4989.The_Red_Tent
Scraping details 230/500: https://www.goodreads.com/book/show/1898.Into_Thin_Air

In [34]:
df2 = pd.DataFrame(detailed_books)

df2.head()

,source_year,rank,list_title,book_url,source,title,author,average_rating,ratings_count,reviews_count,description,genres,pages,published_date,image_url
0,1975,1,’Salem’s Lot,https://www.goodreads.com/book/show/11590._Sal...,Goodreads Popular by Year,’Salem’s Lot,Stephen King,4.10,674093,28812,Librarian's Note: Alternate-cover edition for ...,"Horror, Fiction, Vampires, Fantasy, Thriller, ...",483,"October 17, 1975",https://m.media-amazon.com/images/S/compressed...
1,1975,2,Tuck Everlasting,https://www.goodreads.com/book/show/84981.Tuck...,Goodreads Popular by Year,Tuck Everlasting,Natalie Babbitt,3.91,299733,13997,Introduced by New York Times –bestselling auth...,"Fantasy, Classics, Young Adult, Fiction, Child...",148,"January 1, 1975",https://m.media-amazon.com/images/S/compressed...
2,1975,3,"Shōgun (Asian Saga, #1)",https://www.goodreads.com/book/show/52382796-s...,Goodreads Popular by Year,Shōgun,James Clavell,4.41,217483,9063,After Englishman John Blackthorne is lost at s...,"Historical Fiction, Fiction, Japan, Historical...",1152,"January 1, 1975",https://m.media-amazon.com/images/S/compressed...
3,1975,4,Factotum,https://www.goodreads.com/book/show/497199.Fac...,Goodreads Popular by Year,Factotum,Charles Bukowski,3.92,77117,3254,"One of Bukowski's best, this beer-soaked, deli...","Fiction, Classics, Novels, Literature, America...",205,"January 1, 1975",https://m.media-amazon.com/images/S/compressed...
4,1975,5,Discipline and Punish: The Birth of the Prison,https://www.goodreads.com/book/show/80369.Disc...,Goodreads Popular by Year,Discipline and Punish: The Birth of the Prison,Michel Foucault,4.23,37806,1914,Librarian note: an alternate cover for this ed...,"Philosophy, Nonfiction, History, Sociology, Th...",333,"January 1, 1975",https://m.media-amazon.com/images/S/compressed...

In [35]:
df2.to_csv("data/raw/goodreads_books_detailed1.csv", index=False)

* Cleaning data and columns

In [9]:
df2 = pd.read_csv("data/raw/goodreads_books_detailed1.csv")
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   source_year     500 non-null    int64
 1   rank            500 non-null    int64
 2   list_title      500 non-null    str
 3   book_url        500 non-null    str
 4   source          500 non-null    str
 5   title           500 non-null    str
 6   author          500 non-null    str
 7   average_rating  500 non-null    float64
 8   ratings_count   500 non-null    int64
 9   reviews_count   500 non-null    int64
 10  description     500 non-null    str
 11  genres          500 non-null    str
 12  pages           500 non-null    int64
 13  published_date  500 non-null    str
 14  image_url       500 non-null    str
dtypes: float64(1), int64(5), str(9)
memory usage: 681.6 KB

In [ ]:
df2 = df2.drop(columns=["list_title", "rank", "published_date"]) # dropping columns not needed
df2["title"].value_counts().head(20)  #  There are some duplicate books. We have to drop them!

title
The Host                                                3
The BFG                                                 2
Pet Sematary                                            2
The Witches                                             2
If You Give a Mouse a Cookie                            2
Matilda                                                 2
The Pillars of the Earth                                2
The Firm                                                2
The Last Wish                                           2
The Power of Now: A Guide to Spiritual Enlightenment    2
City of Ashes                                           2
City of Glass                                           2
The Song of Achilles                                    2
Shadow and Bone                                         2
The Wedding People                                      2
’Salem’s Lot                                            1
Tuck Everlasting                                        1
Shōgun                                                  1
Factotum                                                1
Discipline and Punish: The Birth of the Prison          1
Name: count, dtype: int64

In [ ]:
duplicate_titles = df2[df2["title"].duplicated(keep=False)].sort_values("title")
duplicate_titles[["title", "author", "source_year", "average_rating", "ratings_count", "source"]].head(29)  # For sure we have to drop them

,title,author,source_year,average_rating,ratings_count,source
335,City of Ashes,Cassandra Clare,2008,4.10,1004685,Goodreads Popular by Year
336,City of Ashes,Cassandra Clare,2008,4.10,1004685,Goodreads Popular by Year
347,City of Glass,Cassandra Clare,2009,4.27,1023498,Goodreads Popular by Year
348,City of Glass,Cassandra Clare,2009,4.27,1023498,Goodreads Popular by Year
108,If You Give a Mouse a Cookie,Laura Joffe Numeroff,1985,4.30,317240,Goodreads Popular by Year
109,If You Give a Mouse a Cookie,Laura Joffe Numeroff,1985,4.30,317240,Goodreads Popular by Year
131,Matilda,Roald Dahl,1988,4.34,1133306,Goodreads Popular by Year
133,Matilda,Roald Dahl,1988,4.34,1133306,Goodreads Popular by Year
80,Pet Sematary,Stephen King,1983,4.09,718110,Goodreads Popular by Year
81,Pet Sematary,Stephen King,1983,4.09,718110,Goodreads Popular by Year
376,Shadow and Bone,Leigh Bardugo,2012,3.91,1132891,Goodreads Popular by Year
377,Shadow and Bone,Leigh Bardugo,2012,3.91,1132891,Goodreads Popular by Year
72,The BFG,Roald Dahl,1982,4.23,535191,Goodreads Popular by Year
134,The BFG,Roald Dahl,1988,4.23,535191,Goodreads Popular by Year
169,The Firm,John Grisham,1991,4.26,118887,Goodreads Popular by Year
204,The Firm,Robin Waterfield ( Adaptor ),1995,4.07,639776,Goodreads Popular by Year
337,The Host,Stephenie Meyer,2008,3.86,1054829,Goodreads Popular by Year
338,The Host,Stephenie Meyer,2008,3.86,1054829,Goodreads Popular by Year
339,The Host,Stephenie Meyer,2008,3.86,1054829,Goodreads Popular by Year
183,The Last Wish,Andrzej Sapkowski,1993,4.14,427698,Goodreads Popular by Year
184,The Last Wish,Andrzej Sapkowski,1993,4.14,427698,Goodreads Popular by Year
141,The Pillars of the Earth,Ken Follett,1989,4.35,846582,Goodreads Popular by Year
142,The Pillars of the Earth,Ken Follett,1989,4.35,846582,Goodreads Popular by Year
226,The Power of Now: A Guide to Spiritual Enlight...,Eckhart Tolle,1997,4.15,464912,Goodreads Popular by Year
227,The Power of Now: A Guide to Spiritual Enlight...,Eckhart Tolle,1997,4.15,464912,Goodreads Popular by Year
361,The Song of Achilles,Madeline Miller,2011,4.30,2092352,Goodreads Popular by Year
362,The Song of Achilles,Madeline Miller,2011,4.30,2092352,Goodreads Popular by Year
492,The Wedding People,Alison Espach,2024,4.07,1263370,Goodreads Popular by Year
493,The Wedding People,Alison Espach,2024,4.07,1263370,Goodreads Popular by Year

In [15]:
df2_clean = df2.drop_duplicates(
    subset=["title", "author"],
    keep="first"
).reset_index(drop=True)

In [16]:
df2_clean[["title", "author"]].duplicated().sum()

np.int64(0)

In [17]:
df2_clean["title"].value_counts().head(20)

title
The Firm                                                                     2
’Salem’s Lot                                                                 1
Tuck Everlasting                                                             1
Shōgun                                                                       1
Factotum                                                                     1
Discipline and Punish: The Birth of the Prison                               1
Crocodile on the Sandbank                                                    1
Forever...                                                                   1
Where Are the Children?                                                      1
The Miracle of Mindfulness: An Introduction to the Practice of Meditation    1
Danny the Champion of the World                                              1
Interview with the Vampire                                                   1
The Selfish Gene                                                             1
Children of Dune                                                             1
Roots: The Saga of an American Family                                        1
Roll of Thunder, Hear My Cry                                                 1
All Things Bright and Beautiful                                              1
The Omen                                                                     1
On Writing Well: The Classic Guide to Writing Nonfiction                     1
A Course in Miracles: Combined Volume                                        1
Name: count, dtype: int64

In [ ]:
df2_clean = df2_clean[df2_clean["description"] != "1"].copy() #  Droppping a description == 1

* Saving Clean dataset

In [19]:
df2_clean.to_csv("data/GoodBooks_clean.csv", index=False)